-- Autogenerated Instantiation Template for register
-- Generated by gen_instance.py (available here: ##GITHUB##)
-- Original Source File: /home/joehi/fpga-scripts/example_src/test.vhd

u_register : entity work.register
    Generic map (
        G_WIDTH => G_WIDTH
)
    Port map (
        clk_in => clk_in,
        d_in => d_in,
        d_out => d_out
);

